### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by topazcoding** [adamjmurray/ableton-midi-clip-variator#2]
Hi Adam

(sorry it was not working but redownloaded and is now)

This is neat, it would neat if there was a way to vary note pitch ;-)

cheers
Matt

**Comment by adamjmurray** [comment]
Oh, good to hear! I just got around to double checking this tonight and I thought it should work...

Just make sure you have the .amxd and .js file in the same folder. That might have been the problem.

For varying note pitch, yes I agree! I'm actually working on a new Max for Live device that expands on this one and adds a lot more features, including varying pitch. I might need some beta testers soon, if you are interested.

**Comment by topazcoding** [comment]
Hi Adam thanks for your reply I did get it working and I edited the post
but I couldn't work out how to edit the title.

 The ability to select a range of notes i.e. the last quarter bar in a drum
pattern and shuffle randomise   The pitch is velocity and even length would
be great.

Main use for me at least  would be to add a variation to sliced up drum
loops,  melodies, etc.

 I would love to help test just let me know when you're ready.

all the best Matt

**Comment by adamjmurray** [comment]
I'm not sure if this is what you meant, but did you know you can select some notes, and this device will only change the selected notes? It selects them all when nothing is selected.

I'm closing this issue since it's working for you now. Open a new one if you run into other problems.

**Comment by topazcoding** [comment]
Hi Adam, yes I knew :-)

Look forward to testing the pitch shuffling.

Warm regards
Matt
